"""boards3

Revision ID: 445073be0047
Revises: f91d8606e61e
Create Date: 2024-04-26 15:48:44.424727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '445073be0047'
down_revision: Union[str, None] = 'f91d8606e61e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('board', 'white',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('board', 'black',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('board', 'black',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('board', 'white',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
