"""invitations2

Revision ID: 17dcc7874a0b
Revises: 828d5bcdbb16
Create Date: 2024-04-26 23:40:06.164546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17dcc7874a0b'
down_revision: Union[str, None] = '828d5bcdbb16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invitation', 'uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitation', sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
