"""boards2

Revision ID: f91d8606e61e
Revises: 7407de2c453f
Create Date: 2024-04-26 15:44:44.569837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f91d8606e61e'
down_revision: Union[str, None] = '7407de2c453f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('owner', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('privacy', sa.String(), nullable=False),
    sa.Column('invited', sa.String(), nullable=False),
    sa.Column('white', sa.Uuid(), nullable=False),
    sa.Column('black', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('board')
    # ### end Alembic commands ###
