"""moves

Revision ID: 828d5bcdbb16
Revises: 73f57873c018
Create Date: 2024-04-26 20:28:28.071796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '828d5bcdbb16'
down_revision: Union[str, None] = '73f57873c018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('move',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('board', sa.Uuid(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('src', sa.String(), nullable=False),
    sa.Column('dst', sa.String(), nullable=False),
    sa.Column('figure', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['board'], ['board.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('move')
    # ### end Alembic commands ###
